name: Mechanics Shop CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main #Setting on Push to main branch, run our jobs


jobs: #The things we want to happen on push
  build:
    runs-on: ubuntu-latest #Ubuntu is a widely used linux distribution that is heavily support and has alot of prebuilt Github actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' #setting up python on our build environment

      - name: Create virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: print debugging info
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Content of Working Directory: $(ls -l)"
          echo "Contents of site-package: $(ls -l venv/lib/python*/site-packages)"

        test: 
          needs: build
          runs-on: ubuntu-latest

          steps: 
          - name: Checkout code
            uses: actions/checkout@v2

            -name: set up python
            uses: actions/setup-python@v2
            with: 
              python-version: '3.8'
            - name: Create virtual Environment
          run: |
          python -m pip install --upgrade pip 
          python -m pip install -r requirements.txt
      
      - name: Run unit tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests -p '*_test.py'
